import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import LocalFont from "next/font/local";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Link from "next/link";
import { Home, User2 } from "lucide-react";
import { LogoutButton } from "@/components/logout-button";

const pretendard = LocalFont({
  src: "../public/fonts/PretendardVariable.woff2",
  variable: "--font-pretendard",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${pretendard.className} antialiased flex bg-gray-400`}>
        <div className="max-w-[430px] relative w-full mx-auto bg-[#101c3e] h-[100dvh] flex flex-col">
          <Toaster position="top-right" />
          <div className="flex mb-auto py-2 h-min absolute w-full z-10">
            <div className="mx-auto flex items-center gap-x-1">
              <Link
                href={"/"}
                className="border bg-white p-2 rounded-full opacity-50 cursor-pointer"
              >
                <Home />
              </Link>
              <Link
                href={"/profile"}
                className="border bg-white p-2 rounded-full opacity-50 cursor-pointer"
              >
                <User2 />
              </Link>
              <div className="border bg-white p-2 rounded-full opacity-50 cursor-pointer">
                <LogoutButton />
              </div>
            </div>
          </div>
          <div className="h-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
